[package]
name = "ujson"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.117"
thiserror = "1.0.61"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "bench"
harness = false

[profile.release]
opt-level = 3
lto = true
